package com.starter.performance.exception;

public enum AuthErrorCode {
    EMAIL_IS_DUPLICATED_EXCEPTION,
    NICKNAME_IS_DUPLICATED_EXCEPTION,
    UNSUBSCRIBED_EMAIL_EXCEPTION,
    WRONG_PASSWORD_EXCEPTION,
    AUTHENTICATION_IS_FAILED_EXCEPTION,
    ACCESS_IS_DENIED_EXCEPTION
}
