package com.starter.performance.exception;

public enum MemberErrorType {

  WRONG_PASSWORD_EXCEPTION,

  INVALID_MEMBER_EXCEPTION,

  INVALID_PASSWORD_EXCEPTION,

  INVALID_PHONE_NUMBER_EXCEPTION,

  INVALID_NICKNAME_EXCEPTION,

  NICKNAME_IS_DUPLICATED_EXCEPTION,

  ALREADY_WITHDRAWAL_EXCEPTION,

  ALREADY_SANCTION_EXCEPTION;
}
